language: ruby
rvm:
  - 1.9.3
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
env:
  - S3_BUCKET=crabbucket S3_ACCESS_KEY=Foo S3_SECRET=Bar
before_script:
  - psql -c 'create database user_service_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
